spring:
  datasource:
   url: jdbc:mysql://172.16.252.182:3210/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true
   username: root
   password: fjcqt@1234
   driver-class-name: com.mysql.cj.jdbc.Driver

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
